[Paths]                                                     
Prefix = C:/Mlops Day 1/workshop_mlops                                      
Documentation = C:/Mlops Day 1/workshop_mlops/Library/share/doc/qt6         
Headers = C:/Mlops Day 1/workshop_mlops/Library/include/qt6                            
Libraries = C:/Mlops Day 1/workshop_mlops/Library/lib                              
LibraryExecutables = C:/Mlops Day 1/workshop_mlops/Library/lib/qt6                 
Binaries = C:/Mlops Day 1/workshop_mlops/Library/lib/qt6/bin                       
Plugins = C:/Mlops Day 1/workshop_mlops/Library/lib/qt6/plugins                    
QmlImports = C:/Mlops Day 1/workshop_mlops/Library/lib/qt6/qml                     
ArchData = C:/Mlops Day 1/workshop_mlops/Library/lib/qt6                           
Data = C:/Mlops Day 1/workshop_mlops/Library/share/qt6                      
Translations = C:/Mlops Day 1/workshop_mlops/Library/share/qt6/translations 
Examples = C:/Mlops Day 1/workshop_mlops/Library/share/doc/qt6/examples     
Tests = C:/Mlops Day 1/workshop_mlops/Library/tests                         
HostData = C:/Mlops Day 1/workshop_mlops/Library/lib/qt6                    
HostBinaries = C:/Mlops Day 1/workshop_mlops/Library/lib/qt6/bin                   
HostLibraryExecutables = C:/Mlops Day 1/workshop_mlops/Library/lib/qt6             
HostLibraries = C:/Mlops Day 1/workshop_mlops/Library/lib                          
